### ISSUE TITLE
Template params break firebase storage url encoded strings

### ISSUE THREAD

**Issue by andrewspy** [unjs/unhead#137]
### Environment

nuxt v3.3.1

### Reproduction

Following is the source url from firebase storage for `og:image`:

https://firebasestorage.googleapis.com/v0/b/buuger.appspot.com/o/accounts%2Ffotobuukmy%2Fseries%2Fwedding-studio%2Fbuuks%2Fapril-film-studio%2Fcover.jpg?alt=media&token=8b93a6d5-dec2-4f28-9792-4568d73eeb5b

after useHead():

https://firebasestorage.googleapis.com/v0/b/buuger.appspot.com/o/accounts-studio-film-studio?alt=media&token=8b93a6d5-dec2-4f28-9792-4568d73eeb5b

### Describe the bug

firebase storage uses `%` in the URL and it shouldn't be replaced in any way.

### Additional context

I am using nuxt v3.3.1, which uses unhead underneath (not sure which version). I wonder if there is a way to disable the template feature or escape the literal `%` in the string.

**Comment by harlan-zw** [comment]
Hey @andrewspy 

This should have been fixed in the latest Unhead version, but your Nuxt may not be using it yet. Could you do `npm why unhead` and check that you're using [v1.1.23](https://github.com/unjs/unhead/releases/tag/v1.1.23). If not then try delete lock file & re-isntall.

**Comment by andrewspy** [comment]
@harlan-zw Thanks for the quick response, below is my output of `pnpm why unhead`, It seems the problem is still present.

```
dependencies:
@vueuse/nuxt 9.4.0
└─┬ nuxt 3.3.1 peer
  └─┬ @unhead/vue 1.1.23
    └── unhead 1.1.23

devDependencies:
nuxt 3.3.1
└─┬ @unhead/vue 1.1.23
  └── unhead 1.1.23
```

**Comment by harlan-zw** [comment]
A fix is available in https://github.com/unjs/unhead/commit/fee3e838f1abfff84b02b7f4227867be6bc6e6b0, I'll try get a release out tomorrow

**Comment by harlan-zw** [comment]
Fix is available in 1.1.25, please let me know if you have any further issues with it though.

**Comment by andrewspy** [comment]
@harlan-zw tested and everything is working as expected in 1.1.25. Thanks a lot!
