### ISSUE TITLE
Adding an empty style throws error

### ISSUE THREAD

**Issue by sharifzadesina** [unjs/unhead#324]
### Environment

Doesn't matter.

### Reproduction

```js
useHead({
  bodyAttrs: {
    style: ''
  }
});
```

### Describe the bug

Same as the nuxt/nuxt#15488, if you provide an empty string for style property, it throws an error `value.split is not a function`.

We need to change
`for (const c of value.split(';').filter(Boolean))`
to
`for (const c of (value || '').split(' ').filter(Boolean)) {`
Same as `class` attribute.

**Comment by harlan-zw** [comment]
Thanks, this should be fixed in 1.8.12

**Comment by sharifzadesina** [comment]
@harlan-zw 
Unfortunately, unlike the case for `class` attribute, This didn't fix the error for `style`.
I don't know why but empty style is converted to boolean `true` somewhere, `{class: '', style: true}`.
So the code `for (const c of (value || '').split(' ').filter(Boolean)) {` actually does nothing.

**Comment by sharifzadesina** [comment]
@harlan-zw I did a bit of debugging, it seems something is wrong inside `normalizeTag` it converts empty string to boolean `true`.

**Comment by harlan-zw** [comment]
Sorry about this, I only had a short amount of time and didn't test the fix properly.

I've now pushed a proper fix and also added support for handling styles similar to classes with minimal runtime overhead.

Meaning, you can now do things like this:

```ts
const isNavActive = ref(false)
useHead({
  bodyAttrs: {
    style: {
      'color': 'white',
      // fully reactive styles
      'background-color': () => isNavActive.value ? 'red' : '',
    },
  },
})
```
