### ISSUE TITLE
Can't access component data via `this` in Vue 2 using the options api

### ISSUE THREAD

**Issue by kleinepls** [unjs/unhead#400]
### Environment

Node v18.17.1
Vue 2.7.16
@unhead/vue 1.11.2

### Reproduction

https://github.com/kleinepls/unhead-vue2

### Describe the bug

To reproduce, just uncomment line 24 from `App.vue` from the linked repo and `this` should result to `undefined`.

After making the repo I re-checked the docs and it technically never shows that you can access the `data` property, so I'm wondering if this is a missing feature?

**Comment by harlan-zw** [comment]
Hey, thanks for the issue. This should be fixed in v1.11.3.

**Comment by kleinepls** [comment]
Hi, thanks for taking a look. I think it's still not working though :( I've tested in 1.11.3 and 1.11.6. I've updated my repo if you want to check quickly

**Comment by overclocked555** [comment]
Vue 2.7.16 @unhead/vue 1.11.6 still not working for me too

**Comment by harlan-zw** [comment]
Sorry it looks like I didn't investigate this properly initially, I've had another look and pushed up a fix.
